import os
j = os.path.join

homedir = os.path.expanduser('~')

personal		= j(homedir,'.glamour')
saves			= j(personal,'saves')
cache			= j(personal, 'cache')

main			= j('/','home','nelson','glamour')



data			= j(main,'data')
images			= j(main,'data','images')
effects			= j(main,'data','images','effects')
kiss			= j(main,'data','images','effects','kiss')
dirt			= j(main,'data','images','effects','dirt')
princess		= j(main,'data','images','princess')
credits			= j(main,'data','images','credits')
enemies			= j(main,'data','images','enemies')
interface		= j(main,'data','images','interface')
icons			= j(main,'data','images','interface','icons')
omni_interface	= j(main,'data','images','interface','omni')
drapes			= j(main,'data','images','interface','omni','drapes','rendered_drapes')
upper_drapes	= j(main,'data','images','interface','omni','drapes','upper_drapes')
left_bar		= j(main,'data','images','interface','omni','left_bar')
title_screen	= j(main,'data','images','interface','title_screen')
button_ok		= j(main,'data','images','interface','title_screen','button_ok')
button_cancel	= j(main,'data','images','interface','title_screen','button_cancel')
arrow_right		= j(main,'data','images','interface','title_screen','arrow_right')
loading			= j(main,'data','images','interface','loading')
ball			= j(main,'data','images','interface','ball')
boyfriends		= j(main,'data','images','interface','ball','boyfriends')
dancers			= j(main,'data','images','interface','ball','dancers')
fairy_tips		= j(main,'data','images','interface','fairy_tips')
unlocking		= j(main,'data','images','interface','fairy_tips','unlocking')
unlocking_grow	= j(main,'data','images','interface','fairy_tips','unlocking','grow')
unlocking_run 	= j(main,'data','images','interface','fairy_tips','unlocking','run')
star			= j(main,'data','images','interface','star')
closet			= j(main,'data','images','interface','closet')
effects			= j(main,'data','images','effects')
reference		= j(main,'data','images','reference')
scenario		= j(main,'data','images','scenario')
skies			= j(main,'data','images','scenario','skies')
nimbus			= j(main,'data','images','scenario','skies','nimbus')
ballroom		= j(main,'data','images','scenario','ballroom')
omni			= j(main,'data','images','scenario','omni')
gate			= j(main,'data','images','scenario','omni','gate')
story			= j(main,'data','images','story')
story_frames	= j(main,'data','images','story','frames')
tutorial_frames = j(main,'data','images','tutorial','frames')
fonts			= j(main,'data','fonts')
sounds			= j(main,'data','sounds')
music			= j(main,'data','sounds','music')
princess_sounds = j(main,'data','sounds','princess')
